In [1]:
import numpy as np

# Task 1

Q1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [42]:
def divbyzero(numerator,denominator):
    try:
        result = numerator / denominator
    except(ZeroDivisionError):
        return ZeroDivisionError
    print('Division result = ')
    return  result
    
    


In [43]:
divbyzero(100,0) 


ZeroDivisionError

Q2) Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [39]:
subjects = ["Americans", "Indians"]
verb =  ["Play", "watch"] 
objects = ["Baseball","cricket"]            

In [40]:
for i in subjects:
    for j in verb:
        for k in objects:
            print(i + ' ' + j + ' ' + k)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Task 2

Q2)Generate Alexandre-Theophile Vandermonde Matrix

In [95]:
def vandergenerator(input,increasing,n):
    if increasing:
        new = np.array([i**j for i in input for j in range(n) ]).reshape(input.shape[0],n)
    else:
         new = np.array([i**j for i in input for j in range(n-1,-1,-1)]).reshape(input.shape[0],n)
    return new        
    

In [97]:
input = np.array([2,4,6,8])

print('Input array:',input)
print('\nNumber of Columns required:',4)
print('\nGenerating Output Matrix with Increasing set as',False)
print(vandergenerator(input,False,5))

print("\n\n*************************************************************************************\n\n")

print('Input array:',input)
print('\nNumber of Columns required:',5)
print('\nGenerating Output Matrix with Increasing set as',True)
print(vandergenerator(input,True,5))

Input array: [2 4 6 8]

Number of Columns required: 4

Generating Output Matrix with Increasing set as False
[[  16    8    4    2    1]
 [ 256   64   16    4    1]
 [1296  216   36    6    1]
 [4096  512   64    8    1]]


*************************************************************************************


Input array: [2 4 6 8]

Number of Columns required: 5

Generating Output Matrix with Increasing set as True
[[   1    2    4    8   16]
 [   1    4   16   64  256]
 [   1    6   36  216 1296]
 [   1    8   64  512 4096]]
